# Uncomment the next line to define a global platform for your project
# platform :ios, '14.1'

target 'ArticleMemory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArticleMemory
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.0.0-rc.3'

  target 'ArticleMemoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArticleMemoryUITests' do
    # Pods for testing
  end

end
